language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  include:
    - php: 5.5
      dist: trusty
  allow_failures:
    - php: nightly

install:
    - composer require "php-http/guzzle6-adapter:^1.0" --no-update
    - composer --prefer-source install

notifications:
  email:
    - payumsupport@forma-pro.com
