language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: hhvm

before_install:
    - composer self-update

install:
    - composer require "php-http/guzzle6-adapter:^1.0" --no-update
    - composer --prefer-source install

notifications:
  email:
    - payumsupport@forma-pro.com
